name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.overview.svg
          token: ${{ secrets.METRICS_TOKEN }}
          name: Detailed display
          plugin_achievements: yes
          plugin_lines: yes
          plugin_languages_indepth: yes
          plugin_languages: yes
          plugin_languages_ignored: TCL, CMake, CSS, Mathematica
          commits_authoring: lachlan jowett, lochyj, lachlan@jowett.net.au, lochyjowett1@gmail.com, 
